### ISSUE TITLE
HwpSummaryInformation 에러

### ISSUE THREAD

**Issue by hyuunnn** [mete0r/pyhwp#161]
```
Traceback (most recent call last):
  File "C:\Users\hy00un\Desktop\hwp\pyhwp\hwp5proc-script.py", line 11, in <module>
    load_entry_point('pyhwp==0.1b10.dev0', 'console_scripts', 'hwp5proc')()
  File "C:\python27\lib\site-packages\pyhwp-0.1b10.dev0-py2.7.egg\hwp5\proc\__init__.py", line 188, in main
    return main(args)
  File "C:\python27\lib\site-packages\pyhwp-0.1b10.dev0-py2.7.egg\hwp5\proc\summaryinfo.py", line 46, in main
    for textline in formatter.formatTextLines(hwpfile.summaryinfo):
  File "C:\python27\lib\site-packages\pyhwp-0.1b10.dev0-py2.7.egg\hwp5\utils.py", line 55, in __get__
    value = self.func(obj)
  File "C:\python27\lib\site-packages\pyhwp-0.1b10.dev0-py2.7.egg\hwp5\filestructure.py", line 552, in summaryinfo
    return self['\005HwpSummaryInformation']
  File "C:\python27\lib\site-packages\pyhwp-0.1b10.dev0-py2.7.egg\hwp5\storage\__init__.py", line 53, in __getitem__
    item = self.wrapped[name]
  File "C:\python27\lib\site-packages\pyhwp-0.1b10.dev0-py2.7.egg\hwp5\storage\__init__.py", line 53, in __getitem__
    item = self.wrapped[name]
  File "C:\python27\lib\site-packages\pyhwp-0.1b10.dev0-py2.7.egg\hwp5\storage\__init__.py", line 53, in __getitem__
    item = self.wrapped[name]
  File "C:\python27\lib\site-packages\pyhwp-0.1b10.dev0-py2.7.egg\hwp5\storage\__init__.py", line 53, in __getitem__
    item = self.wrapped[name]
  File "C:\python27\lib\site-packages\pyhwp-0.1b10.dev0-py2.7.egg\hwp5\storage\ole.py", line 41, in __getitem__
    return self.impl.__getitem__(name)
  File "C:\python27\lib\site-packages\pyhwp-0.1b10.dev0-py2.7.egg\hwp5\plat\olefileio.py", line 127, in __getitem__
    raise KeyError('%s not found' % path)
KeyError: u'\x05HwpSummaryInformation not found'
```
소스 코드를 확인 한 결과 \005HwpSummaryInformation 해당 이름만 비교하여 탐지를 못해서
IHwpSummaryInformation을 추가로 비교하여 해결했습니다.

컨트리뷰트 하다가 꼬여서 issue로 옮겼습니다.

```
if name == '\005HwpSummaryInformation' or name == 'IHwpSummaryInformation':
            return self.with_version(self.summaryinfo_class)
```
```
@cached_property
    def summaryinfo(self):
        try:
            return self['\005HwpSummaryInformation']
        except:
            return self['IHwpSummaryInformation']
```

**Comment by mete0r** [comment]
리포트 감사합니다.

해당 파일은 \005 문자 대신 대문자 I를 사용하고 있는 것으로 보이는데, 이것이 한컴 측의 공식 변경 사항(최근 버젼 한글 프로그램 및 문서 포맷)인지를 확인할 필요가 있는 것 같습니다. 문서 해킹 등의 목적으로 파일 내용이 공식 버젼과는 달리 바뀌는 경우들이 있는 것 같아서 그렇습니다.

그래서 다음을 알려주실 수 있으면 좋습니다.

1. 해당 에러가 발생하는 HWP 파일을 보내주실 수 있을까요.
2. 1.이 어렵다면, 해당 에러가 발생하는 HWP 파일의 파일 포맷 버젼을 알려주십시오. hwp5proc version 명령으로 확인 가능합니다.
3. 가능하다면, 해당 HWP 파일을 생성한 한글 프로그램 버젼도 알려주시면 좋습니다.

감사합니다.

**Comment by hy00un** [comment]
해당 hwp 파일 버전은 5.0.2.2 입니다.
hwp 악성 파일 분석 도중에 발생했던 오류인데 답변해주신 글을 읽어보니, 인위적으로 \005가 아닌 I로 조작했을 가능성도 있겠네요.
표준 문서도 \005로 되어있네요 ㅎㅎ.. 감사합니다.
