### ISSUE TITLE
Hwp5odt undefined Kind value: 6, hwp5.errors.ValidationFailed: RelaxNG

### ISSUE THREAD

**Issue by qubcia** [mete0r/pyhwp#177]
pyHWP 0.1b14 패키지를 설치하고, 표와 테이블로 구성된 아래한글 문서에 대한 hwp5odt 명령어 실행 시, 아래와 같은 변환 에러가 발생합니다.

# hwp5odt ABC.hwp
undefined Kind value: 6
defined name/values: {'PAGE': Kind.PAGE, 'FOOTNOTE': Kind.FOOTNOTE, 'ENDNOTE': Kind.ENDNOTE, 'PICTURE': Kind.PICTURE, 'TABLE': Kind.TABLE, 'EQUATION': Kind.EQUATION}
 <string>:2:0:ERROR:RELAXNGV:RELAXNG_ERR_EXTRACONTENT: Element p has extra content: rect
 Traceback (most recent call last):
   File "/usr/local/bin/hwp5odt", line 11, in <module>
     load_entry_point('pyhwp==0.1b14', 'console_scripts', 'hwp5odt')()
   File "/usr/local/lib/python3.6/site-packages/hwp5/hwp5odt.py", line 365, in main
     transform(hwp5file, dest)
   File "/usr/local/lib/python3.6/site-packages/hwp5/hwp5odt.py", line 143, in transform_hwp5_to_package
     self.transform_xhwp5_into_package(xml_path, odtpkg)
   File "/usr/local/lib/python3.6/site-packages/hwp5/hwp5odt.py", line 189, in transform
     with self.transformed_content_at_temp(xhwp5path) as path:
   File "/usr/lib64/python3.6/contextlib.py", line 81, in __enter__
     return next(self.gen)
   File "/usr/local/lib/python3.6/site-packages/hwp5/hwp5odt.py", line 238, in transformed_at_temp_path
     transform(inp_path, f)
   File "/usr/local/lib/python3.6/site-packages/hwp5/hwp5odt.py", line 229, in validating_transform
     transform(input, output)
   File "/usr/lib64/python3.6/contextlib.py", line 88, in __exit__
     next(self.gen)
   File "/usr/local/lib/python3.6/site-packages/hwp5/plat/_lxml.py", line 146, in validating_output
     raise ValidationFailed('RelaxNG')
 hwp5.errors.ValidationFailed: RelaxNG

**Comment by mete0r** [comment]
리포팅 감사합니다.

위 에러가 발생하는 hwp 파일의 포맷 버젼을 알려주셨으면 합니다.

파일의 포맷 버젼은

`hwp5proc version FILENAME`

으로 확인할 수 있습니다.

**Comment by qubcia** [comment]
상기 명령 실행 결과, 버전은 5.1.0.1 입니다.

**Comment by qubcia** [comment]
0.1b15 (2020-05-30)
Unknown Numbering.Kind value of 6, which is not described in the official specification docs, has been added.

**Comment by qubcia** [comment]
상기 버전으로 업데이트하고 실행했으나, 아래와 같은 에러가 발생합니다.
# hwp5odt --version
hwp5odt 0.1b15

# hwp5odt ABC.hwp (아래한글 파일을 받을 수 있는 메일주소 요청)
 <string>:2:0:ERROR:RELAXNGV:RELAXNG_ERR_EXTRACONTENT: Element p has extra content: rect
 Traceback (most recent call last):
   File "/usr/local/bin/hwp5odt", line 11, in <module>
     load_entry_point('pyhwp==0.1b15', 'console_scripts', 'hwp5odt')()
   File "/usr/local/lib/python3.6/site-packages/hwp5/hwp5odt.py", line 365, in main
     transform(hwp5file, dest)
   File "/usr/local/lib/python3.6/site-packages/hwp5/hwp5odt.py", line 143, in transform_hwp5_to_package
     self.transform_xhwp5_into_package(xml_path, odtpkg)
   File "/usr/local/lib/python3.6/site-packages/hwp5/hwp5odt.py", line 189, in transform
     with self.transformed_content_at_temp(xhwp5path) as path:
   File "/usr/lib64/python3.6/contextlib.py", line 81, in __enter__
     return next(self.gen)
   File "/usr/local/lib/python3.6/site-packages/hwp5/hwp5odt.py", line 238, in transformed_at_temp_path
     transform(inp_path, f)
   File "/usr/local/lib/python3.6/site-packages/hwp5/hwp5odt.py", line 229, in validating_transform
     transform(input, output)
   File "/usr/lib64/python3.6/contextlib.py", line 88, in __exit__
     next(self.gen)
   File "/usr/local/lib/python3.6/site-packages/hwp5/plat/_lxml.py", line 146, in validating_output
     raise ValidationFailed('RelaxNG')
 hwp5.errors.ValidationFailed: RelaxNG

**Comment by qubcia** [comment]
#178 참조.
