### ISSUE TITLE
ERROR:RELAXNGV:RELAXNG_ERR_EXTRACONTENT 에러가 발생합니다.

### ISSUE THREAD

**Issue by qubcia** [mete0r/pyhwp#178]
0.1b15 버전에서 실행했으나, 아래와 같은 에러가 발생합니다.
# hwp5odt --version
hwp5odt 0.1b15

# hwp5odt ABC.hwp
:2:0:ERROR:RELAXNGV:RELAXNG_ERR_EXTRACONTENT: Element p has extra content: rect
 Traceback (most recent call last):
 File "/usr/local/bin/hwp5odt", line 11, in 
 load_entry_point('pyhwp==0.1b15', 'console_scripts', 'hwp5odt')()
 File "/usr/local/lib/python3.6/site-packages/hwp5/hwp5odt.py", line 365, in main
 transform(hwp5file, dest)
 File "/usr/local/lib/python3.6/site-packages/hwp5/hwp5odt.py", line 143, in transform_hwp5_to_package
 self.transform_xhwp5_into_package(xml_path, odtpkg)
 File "/usr/local/lib/python3.6/site-packages/hwp5/hwp5odt.py", line 189, in transform
 with self.transformed_content_at_temp(xhwp5path) as path:
 File "/usr/lib64/python3.6/contextlib.py", line 81, in enter
 return next(self.gen)
 File "/usr/local/lib/python3.6/site-packages/hwp5/hwp5odt.py", line 238, in transformed_at_temp_path
 transform(inp_path, f)
 File "/usr/local/lib/python3.6/site-packages/hwp5/hwp5odt.py", line 229, in validating_transform
 transform(input, output)
 File "/usr/lib64/python3.6/contextlib.py", line 88, in exit
 next(self.gen)
 File "/usr/local/lib/python3.6/site-packages/hwp5/plat/_lxml.py", line 146, in validating_output
 raise ValidationFailed('RelaxNG')
 hwp5.errors.ValidationFailed: RelaxNG

**Comment by qubcia** [comment]
#177 관련 이슈는 해결되었으나, 상기 오류가 발생하였음

**Comment by mete0r** [comment]
리포팅 감사합니다.

문제가 발생하는 hwp 파일을 공유해주시면 한 번 살펴보겠습니다.

arbeitmachtfrei77@gmail.com

**Comment by qubcia** [comment]
안녕하세요.

이슈가 된 아래한글 파일을 첨부로 보내드립니다.

고맙습니다.

2020년 6월 21일 (일) 오후 5:37, mete0r <notifications@github.com>님이 작성:

**Comment by mete0r** [comment]
이 메시지에 답장을 하시면 메일이 깃허브로 갑니다. 첨부파일이 없네요.

 위에 올린 제 이메일 주소로 직접 첨부파일을 포함하여 메일을 보내주셔야 할 것 같습니다.
