### ISSUE TITLE
우분투 python3.8에서 hwp5odt(0.1b15)명령실행시 일부는 되지만 일부는 다음과 같은 오류가 발생합니다. 혹시 경험하신분 계시면 도움부탁드립니다.

### ISSUE THREAD

**Issue by leejongcheol** [mete0r/pyhwp#182]
hwp5odt  --output=/home/mecissue/apache-tomcat-9.0.40/webapps/odf/tobe/notice/BBS_202012160231295520.odt /home/mecissue/odf/original/BBS_2020121602395520.hwp
<string>:256:0:ERROR:RELAXNGV:RELAXNG_ERR_ELEMNAME: Expecting element map, got text-properties
<string>:254:0:ERROR:RELAXNGV:RELAXNG_ERR_NOELEM: Expecting an element map, got nothing
<string>:255:0:ERROR:RELAXNGV:RELAXNG_ERR_ELEMNAME: Expecting element map, got paragraph-properties
<string>:254:0:ERROR:RELAXNGV:RELAXNG_ERR_INVALIDATTR: Invalid attribute name for element style
<string>:0:0:ERROR:RELAXNGV:RELAXNG_ERR_INTEREXTRA: Extra element style in interleave
<string>:98:0:ERROR:RELAXNGV:RELAXNG_ERR_INTERSEQ: Invalid sequence in interleave
<string>:98:0:ERROR:RELAXNGV:RELAXNG_ERR_CONTENTVALID: Element styles failed to validate content
Traceback (most recent call last):
  File "/opt/anaconda3/bin/hwp5odt", line 8, in <module>
    sys.exit(main())
  File "/opt/anaconda3/lib/python3.8/site-packages/hwp5/hwp5odt.py", line 365, in main
    transform(hwp5file, dest)
  File "/opt/anaconda3/lib/python3.8/site-packages/hwp5/hwp5odt.py", line 143, in transform_hwp5_to_package
    self.transform_xhwp5_into_package(xml_path, odtpkg)
  File "/opt/anaconda3/lib/python3.8/site-packages/hwp5/hwp5odt.py", line 187, in transform
    with self.transformed_styles_at_temp(xhwp5path) as path:
  File "/opt/anaconda3/lib/python3.8/contextlib.py", line 113, in __enter__
    return next(self.gen)
  File "/opt/anaconda3/lib/python3.8/site-packages/hwp5/hwp5odt.py", line 238, in transformed_at_temp_path
    transform(inp_path, f)
  File "/opt/anaconda3/lib/python3.8/site-packages/hwp5/hwp5odt.py", line 229, in validating_transform
    transform(input, output)
  File "/opt/anaconda3/lib/python3.8/contextlib.py", line 120, in __exit__
    next(self.gen)
  File "/opt/anaconda3/lib/python3.8/site-packages/hwp5/plat/_lxml.py", line 146, in validating_output
    raise ValidationFailed('RelaxNG')
hwp5.errors.ValidationFailed: RelaxNG

**Comment by leejongcheol** [comment]
python, anaconda, lxml 모든 버전을 최신으로 바꾸어서 해봐도 오류가 발생 합니다.
혹시 원인을 아시는 분 안계실까요?

**Comment by KevinTheRainmaker** [comment]
4년전 내용 끌올 죄송합니다만 에러 해결하셨을까요? 저도 hwp 파일 중 반 정도가 이 에러로 변환이 안되네요. LibreOffice에서 손상된 파일이라고 안열리는거보면(윈도우에선 잘 열림) 해당 문제 같기도 합니다.

만약 해결된 내용 있으시면 공유 부탁드립니다.
감사합니다.
